name: Deploy to Namecheap Hosting

on:
  push:
    branches:
      - main  # or the branch you want to deploy from

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use the Node.js version compatible with your project

      - name: Install Dependencies
        run: npm ci

      - name: Build React App
        run: npm run build

      - name: Deploy React Build via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp  # Use 'ftp', 'ftps', or 'sftp' as supported by your hosting
          local-dir: build/  # Deploy the React build folder
          server-dir: /public_html/  # The correct directory without an extra folder

      - name: Deploy Projects Folder via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp  # Use 'ftp', 'ftps', or 'sftp' as supported by your hosting
          local-dir: projects/  # Upload only the contents of the 'projects' folder
          server-dir: /public_html/  # The root directory for both the build and projects content
